//! Reads `target/criterion/**/new/{benchmark,estimates}.json` produced by
//! the most recent `cargo bench` and writes a human-readable markdown
//! summary to stdout. Pipe to `BENCH_RESULTS.md` to capture a snapshot.
//!
//! Usage:
//!     cargo bench --bench operations
//!     cargo bench --bench parallelism
//!     cargo run --example bench_report > BENCH_RESULTS.md

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct BenchmarkMeta {
    group_id: String,
    function_id: String,
    full_id: String,
    throughput: Option<Throughput>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
#[allow(dead_code)]
enum Throughput {
    Bytes { #[serde(rename = "Bytes")] bytes: u64 },
    Elements { #[serde(rename = "Elements")] elements: u64 },
}

#[derive(Debug, Deserialize)]
struct Estimates {
    median: PointEstimate,
}

#[derive(Debug, Deserialize)]
struct PointEstimate {
    point_estimate: f64,
}

#[derive(Debug)]
struct Sample {
    full_id: String,
    function_id: String,
    median_ns: f64,
    throughput_bytes: Option<u64>,
}

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/criterion");
    if !root.exists() {
        eprintln!(
            "no criterion output at {} — run `cargo bench` first",
            root.display()
        );
        std::process::exit(1);
    }

    let mut by_group: BTreeMap<String, Vec<Sample>> = BTreeMap::new();
    walk(&root, &mut by_group);

    if by_group.is_empty() {
        eprintln!("no benchmark data found under {}", root.display());
        std::process::exit(1);
    }

    print_header();
    for (group, samples) in &by_group {
        match group.as_str() {
            "operations" => print_operations(samples),
            g if g.starts_with("parallelism/") => print_parallelism(g, samples),
            other => print_generic(other, samples),
        }
    }
}

fn print_header() {
    let host = host_summary();
    println!("# Bench results");
    println!();
    println!("Generated by `cargo run --example bench_report` from the most");
    println!("recent `cargo bench` output under `target/criterion/`.");
    println!();
    println!("- Host: {host}");
    println!("- Profile: `[profile.bench]` (opt-level 3, thin LTO)");
    println!();
}

fn host_summary() -> String {
    let arch = std::env::consts::ARCH;
    let os = std::env::consts::OS;
    let cores = std::thread::available_parallelism()
        .map(|n| n.get().to_string())
        .unwrap_or_else(|_| "?".to_string());
    format!("{arch}-{os}, {cores} logical cores")
}

fn print_operations(samples: &[Sample]) {
    println!("## operations — String vs. Tokens (per op, on Luke)");
    println!();
    println!("| Operation | Median | Throughput |");
    println!("|-----------|-------:|-----------:|");

    let mut sorted: Vec<&Sample> = samples.iter().collect();
    sorted.sort_by(|a, b| operation_order(&a.function_id).cmp(&operation_order(&b.function_id)));

    for s in sorted {
        let median = format_duration(s.median_ns);
        let thrpt = s
            .throughput_bytes
            .map(|b| format!("{:.1} MiB/s", throughput_mib_per_sec(b, s.median_ns)))
            .unwrap_or_default();
        println!("| `{}` | {} | {} |", s.function_id, median, thrpt);
    }
    println!();
}

fn print_parallelism(group: &str, samples: &[Sample]) {
    println!("## {group}");
    println!();
    println!("| Operation | Serial | Rayon | Speedup |");
    println!("|-----------|-------:|------:|--------:|");

    // function_id looks like "parse/serial", "parse/rayon" — pair by op stem.
    let mut by_op: BTreeMap<String, (Option<&Sample>, Option<&Sample>)> = BTreeMap::new();
    for s in samples {
        let (op, mode) = match s.function_id.rsplit_once('/') {
            Some(parts) => parts,
            None => continue,
        };
        let entry = by_op.entry(op.to_string()).or_default();
        match mode {
            "serial" => entry.0 = Some(s),
            "rayon" => entry.1 = Some(s),
            _ => {}
        }
    }

    let mut order: Vec<String> = by_op.keys().cloned().collect();
    order.sort_by_key(|op| op_index(op));
    for op in order {
        let (serial, rayon) = by_op.remove(&op).unwrap();
        let serial_md = serial
            .map(|s| format_duration(s.median_ns))
            .unwrap_or_else(|| "—".to_string());
        let rayon_md = rayon
            .map(|s| format_duration(s.median_ns))
            .unwrap_or_else(|| "—".to_string());
        let speedup = match (serial, rayon) {
            (Some(s), Some(r)) if r.median_ns > 0.0 => {
                format!("{:.2}×", s.median_ns / r.median_ns)
            }
            _ => "—".to_string(),
        };
        println!("| `{op}` | {serial_md} | {rayon_md} | {speedup} |");
    }
    println!();
}

fn print_generic(group: &str, samples: &[Sample]) {
    println!("## {group}");
    println!();
    println!("| Bench | Median | Throughput |");
    println!("|-------|-------:|-----------:|");
    let mut sorted: Vec<&Sample> = samples.iter().collect();
    sorted.sort_by(|a, b| a.function_id.cmp(&b.function_id));
    for s in sorted {
        let thrpt = s
            .throughput_bytes
            .map(|b| format!("{:.1} MiB/s", throughput_mib_per_sec(b, s.median_ns)))
            .unwrap_or_default();
        println!(
            "| `{}` | {} | {} |",
            s.function_id,
            format_duration(s.median_ns),
            thrpt
        );
    }
    println!();
}

fn walk(root: &Path, out: &mut BTreeMap<String, Vec<Sample>>) {
    let entries = match fs::read_dir(root) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        // Skip criterion's per-bench HTML report folder and other meta dirs.
        if matches!(path.file_name().and_then(|n| n.to_str()), Some("report")) {
            continue;
        }
        let bench_meta = path.join("new/benchmark.json");
        let bench_est = path.join("new/estimates.json");
        if bench_meta.is_file() && bench_est.is_file() {
            if let Some(sample) = load_sample(&bench_meta, &bench_est) {
                out.entry(sample.group_id_owned()).or_default().push(sample);
            }
            continue;
        }
        walk(&path, out);
    }
}

fn load_sample(meta_path: &Path, est_path: &Path) -> Option<Sample> {
    let meta_raw = fs::read_to_string(meta_path).ok()?;
    let meta: BenchmarkMeta = serde_json::from_str(&meta_raw).ok()?;
    let est_raw = fs::read_to_string(est_path).ok()?;
    let est: Estimates = serde_json::from_str(&est_raw).ok()?;
    let throughput_bytes = match meta.throughput {
        Some(Throughput::Bytes { bytes }) => Some(bytes),
        _ => None,
    };
    Some(Sample {
        full_id: meta.full_id,
        function_id: meta.function_id,
        median_ns: est.median.point_estimate,
        throughput_bytes,
    })
}

impl Sample {
    fn group_id_owned(&self) -> String {
        // criterion's full_id is "<group>/<function_id>". The group can
        // contain slashes (e.g. "parallelism/en_ulb"), so split from the
        // function_id end.
        match self.full_id.strip_suffix(&self.function_id) {
            Some(prefix) => prefix.trim_end_matches('/').to_string(),
            None => self.full_id.clone(),
        }
    }
}

fn format_duration(ns: f64) -> String {
    if ns >= 1.0e9 {
        format!("{:.2} s", ns / 1.0e9)
    } else if ns >= 1.0e6 {
        format!("{:.2} ms", ns / 1.0e6)
    } else if ns >= 1.0e3 {
        format!("{:.2} µs", ns / 1.0e3)
    } else {
        format!("{ns:.0} ns")
    }
}

fn throughput_mib_per_sec(bytes: u64, ns: f64) -> f64 {
    if ns <= 0.0 {
        return 0.0;
    }
    let bytes_per_sec = bytes as f64 * 1.0e9 / ns;
    bytes_per_sec / (1024.0 * 1024.0)
}

fn operation_order(function_id: &str) -> (u8, String) {
    // Cluster the pairs together: lex, parse, cst, usj, usx, then the
    // string/tokens pairs.
    let stem = function_id.split('/').next().unwrap_or(function_id);
    let group_idx = match stem {
        "lex" => 0,
        "parse" => 1,
        "cst" => 2,
        "usj" => 3,
        "usx" => 4,
        "lint" => 5,
        "format" => 6,
        "html" => 7,
        "diff" => 8,
        _ => 99,
    };
    (group_idx, function_id.to_string())
}

fn op_index(op: &str) -> u8 {
    match op {
        "parse" => 0,
        "lint" => 1,
        "format" => 2,
        "usj" => 3,
        "usx" => 4,
        "html" => 5,
        _ => 99,
    }
}
