#![allow(dead_code)]

use crate::internal::marker_defs::{MarkerSpec, SpecContext, SpecMarkerKind};

pub(crate) static MARKER_SPECS: &[MarkerSpec] = &[
    MarkerSpec {
        marker: "//",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/optbreak.adoc",
    },
    MarkerSpec {
        marker: "add",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/add.adoc",
    },
    MarkerSpec {
        marker: "addpn",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: true,
        source: "repos_to_compare/tcdocs-main/markers/char/addpn.adoc",
    },
    MarkerSpec {
        marker: "b",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/b.adoc",
    },
    MarkerSpec {
        marker: "bd",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/bd.adoc",
    },
    MarkerSpec {
        marker: "bdit",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/bdit.adoc",
    },
    MarkerSpec {
        marker: "bk",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/bk.adoc",
    },
    MarkerSpec {
        marker: "c",
        kind: SpecMarkerKind::Chapter,
        contexts: &[SpecContext::Scripture, SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cv/c.adoc",
    },
    MarkerSpec {
        marker: "ca",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Chapter],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cv/ca.adoc",
    },
    MarkerSpec {
        marker: "cat",
        kind: SpecMarkerKind::Meta,
        contexts: &[
            SpecContext::Sidebar,
            SpecContext::Footnote,
            SpecContext::CrossReference,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cat/cat.adoc",
    },
    MarkerSpec {
        marker: "cd",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/cd.adoc",
    },
    MarkerSpec {
        marker: "cl",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/cl.adoc",
    },
    MarkerSpec {
        marker: "cls",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/cls.adoc",
    },
    MarkerSpec {
        marker: "cp",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Chapter],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cv/cp.adoc",
    },
    MarkerSpec {
        marker: "d",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/d.adoc",
    },
    MarkerSpec {
        marker: "dc",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/dc.adoc",
    },
    MarkerSpec {
        marker: "ef",
        kind: SpecMarkerKind::Note,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::ChapterContent,
            SpecContext::PeripheralContent,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/note/ef.adoc",
    },
    MarkerSpec {
        marker: "em",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/em.adoc",
    },
    MarkerSpec {
        marker: "esb",
        kind: SpecMarkerKind::Sidebar,
        contexts: &[SpecContext::ChapterContent, SpecContext::PeripheralContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/sbar/esb.adoc",
    },
    MarkerSpec {
        marker: "esbe",
        kind: SpecMarkerKind::Sidebar,
        contexts: &[SpecContext::ChapterContent, SpecContext::PeripheralContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/sbar/esb.adoc",
    },
    MarkerSpec {
        marker: "ex",
        kind: SpecMarkerKind::Note,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::ChapterContent,
            SpecContext::PeripheralContent,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/note/ex.adoc",
    },
    MarkerSpec {
        marker: "f",
        kind: SpecMarkerKind::Note,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::ChapterContent,
            SpecContext::PeripheralContent,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/note/f.adoc",
    },
    MarkerSpec {
        marker: "fdc",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: true,
        source: "repos_to_compare/tcdocs-main/markers/char/fdc.adoc",
    },
    MarkerSpec {
        marker: "fe",
        kind: SpecMarkerKind::Note,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::ChapterContent,
            SpecContext::PeripheralContent,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/note/fe.adoc",
    },
    MarkerSpec {
        marker: "fig",
        kind: SpecMarkerKind::Figure,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::ChapterContent,
            SpecContext::PeripheralContent,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/fig/fig.adoc",
    },
    MarkerSpec {
        marker: "fk",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fk.adoc",
    },
    MarkerSpec {
        marker: "fl",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fl.adoc",
    },
    MarkerSpec {
        marker: "fm",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fm.adoc",
    },
    MarkerSpec {
        marker: "fp",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fp.adoc",
    },
    MarkerSpec {
        marker: "fq",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fq.adoc",
    },
    MarkerSpec {
        marker: "fqa",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fqa.adoc",
    },
    MarkerSpec {
        marker: "fr",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fr.adoc",
    },
    MarkerSpec {
        marker: "ft",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/ft.adoc",
    },
    MarkerSpec {
        marker: "fv",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fv.adoc",
    },
    MarkerSpec {
        marker: "fw",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Footnote],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/fw.adoc",
    },
    MarkerSpec {
        marker: "h",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/h.adoc",
    },
    MarkerSpec {
        marker: "ib",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ib.adoc",
    },
    MarkerSpec {
        marker: "id",
        kind: SpecMarkerKind::Header,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/doc/id.adoc",
    },
    MarkerSpec {
        marker: "ide",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ide.adoc",
    },
    MarkerSpec {
        marker: "ie",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ie.adoc",
    },
    MarkerSpec {
        marker: "iex",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/iex.adoc",
    },
    MarkerSpec {
        marker: "ili",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ili.adoc",
    },
    MarkerSpec {
        marker: "ili1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ili.adoc",
    },
    MarkerSpec {
        marker: "ili2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ili.adoc",
    },
    MarkerSpec {
        marker: "im",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/im.adoc",
    },
    MarkerSpec {
        marker: "imi",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imi.adoc",
    },
    MarkerSpec {
        marker: "imq",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imq.adoc",
    },
    MarkerSpec {
        marker: "imt",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imt.adoc",
    },
    MarkerSpec {
        marker: "imt1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imt.adoc",
    },
    MarkerSpec {
        marker: "imt2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imt.adoc",
    },
    MarkerSpec {
        marker: "imt3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imt.adoc",
    },
    MarkerSpec {
        marker: "imt4",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imt.adoc",
    },
    MarkerSpec {
        marker: "imte",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imte.adoc",
    },
    MarkerSpec {
        marker: "imte1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imte.adoc",
    },
    MarkerSpec {
        marker: "imte2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/imte.adoc",
    },
    MarkerSpec {
        marker: "io",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/io.adoc",
    },
    MarkerSpec {
        marker: "io1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/io.adoc",
    },
    MarkerSpec {
        marker: "io2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/io.adoc",
    },
    MarkerSpec {
        marker: "io3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/io.adoc",
    },
    MarkerSpec {
        marker: "io4",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/io.adoc",
    },
    MarkerSpec {
        marker: "ior",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/ior.adoc",
    },
    MarkerSpec {
        marker: "iot",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/iot.adoc",
    },
    MarkerSpec {
        marker: "ip",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction, SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ip.adoc",
    },
    MarkerSpec {
        marker: "ipc",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ipc.adoc",
    },
    MarkerSpec {
        marker: "ipi",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ipi.adoc",
    },
    MarkerSpec {
        marker: "ipq",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ipq.adoc",
    },
    MarkerSpec {
        marker: "ipr",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ipr.adoc",
    },
    MarkerSpec {
        marker: "iq",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/iq.adoc",
    },
    MarkerSpec {
        marker: "iq1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/iq.adoc",
    },
    MarkerSpec {
        marker: "iq2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/iq.adoc",
    },
    MarkerSpec {
        marker: "iq3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/iq.adoc",
    },
    MarkerSpec {
        marker: "iqt",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/iqt.adoc",
    },
    MarkerSpec {
        marker: "is",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/is.adoc",
    },
    MarkerSpec {
        marker: "is1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/is.adoc",
    },
    MarkerSpec {
        marker: "is2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/is.adoc",
    },
    MarkerSpec {
        marker: "it",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/it.adoc",
    },
    MarkerSpec {
        marker: "jmp",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/jmp.adoc",
    },
    MarkerSpec {
        marker: "k",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/k.adoc",
    },
    MarkerSpec {
        marker: "lf",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lf.adoc",
    },
    MarkerSpec {
        marker: "lh",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lh.adoc",
    },
    MarkerSpec {
        marker: "li",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/li.adoc",
    },
    MarkerSpec {
        marker: "li1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/li.adoc",
    },
    MarkerSpec {
        marker: "li2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/li.adoc",
    },
    MarkerSpec {
        marker: "li3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/li.adoc",
    },
    MarkerSpec {
        marker: "li4",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/li.adoc",
    },
    MarkerSpec {
        marker: "lik",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::List],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/lik.adoc",
    },
    MarkerSpec {
        marker: "lim",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lim.adoc",
    },
    MarkerSpec {
        marker: "lim1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lim.adoc",
    },
    MarkerSpec {
        marker: "lim2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lim.adoc",
    },
    MarkerSpec {
        marker: "lim3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lim.adoc",
    },
    MarkerSpec {
        marker: "lit",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookIntroduction, SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/lit.adoc",
    },
    MarkerSpec {
        marker: "litl",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::List],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/litl.adoc",
    },
    MarkerSpec {
        marker: "liv",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::List],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/liv.adoc",
    },
    MarkerSpec {
        marker: "m",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/m.adoc",
    },
    MarkerSpec {
        marker: "mi",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mi.adoc",
    },
    MarkerSpec {
        marker: "mi1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mi.adoc",
    },
    MarkerSpec {
        marker: "mi2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mi.adoc",
    },
    MarkerSpec {
        marker: "mi3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mi.adoc",
    },
    MarkerSpec {
        marker: "mr",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mr.adoc",
    },
    MarkerSpec {
        marker: "ms",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ms.adoc",
    },
    MarkerSpec {
        marker: "ms1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ms.adoc",
    },
    MarkerSpec {
        marker: "ms2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ms.adoc",
    },
    MarkerSpec {
        marker: "ms3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/ms.adoc",
    },
    MarkerSpec {
        marker: "mt",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mt.adoc",
    },
    MarkerSpec {
        marker: "mt1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mt.adoc",
    },
    MarkerSpec {
        marker: "mt2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mt.adoc",
    },
    MarkerSpec {
        marker: "mt3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mt.adoc",
    },
    MarkerSpec {
        marker: "mt4",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroductionEndTitles,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mt.adoc",
    },
    MarkerSpec {
        marker: "mte",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mte.adoc",
    },
    MarkerSpec {
        marker: "mte1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mte.adoc",
    },
    MarkerSpec {
        marker: "mte2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/mte.adoc",
    },
    MarkerSpec {
        marker: "nb",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/nb.adoc",
    },
    MarkerSpec {
        marker: "nd",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/nd.adoc",
    },
    MarkerSpec {
        marker: "no",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/no.adoc",
    },
    MarkerSpec {
        marker: "ord",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/ord.adoc",
    },
    MarkerSpec {
        marker: "p",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/p.adoc",
    },
    MarkerSpec {
        marker: "pb",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pb.adoc",
    },
    MarkerSpec {
        marker: "pc",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pc.adoc",
    },
    MarkerSpec {
        marker: "periph",
        kind: SpecMarkerKind::Periph,
        contexts: &[SpecContext::Peripheral],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/periph/periph.adoc",
    },
    MarkerSpec {
        marker: "ph",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: true,
        source: "repos_to_compare/tcdocs-main/markers/para/ph.adoc",
    },
    MarkerSpec {
        marker: "pi",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pi.adoc",
    },
    MarkerSpec {
        marker: "pi1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pi.adoc",
    },
    MarkerSpec {
        marker: "pi2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pi.adoc",
    },
    MarkerSpec {
        marker: "pi3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pi.adoc",
    },
    MarkerSpec {
        marker: "pm",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pm.adoc",
    },
    MarkerSpec {
        marker: "pmc",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pmc.adoc",
    },
    MarkerSpec {
        marker: "pmo",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pmo.adoc",
    },
    MarkerSpec {
        marker: "pmr",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pmr.adoc",
    },
    MarkerSpec {
        marker: "pn",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/pn.adoc",
    },
    MarkerSpec {
        marker: "png",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/png.adoc",
    },
    MarkerSpec {
        marker: "po",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/po.adoc",
    },
    MarkerSpec {
        marker: "pr",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/pr.adoc",
    },
    MarkerSpec {
        marker: "pro",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: true,
        source: "repos_to_compare/tcdocs-main/markers/char/pro.adoc",
    },
    MarkerSpec {
        marker: "q",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/q.adoc",
    },
    MarkerSpec {
        marker: "q1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/q.adoc",
    },
    MarkerSpec {
        marker: "q2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/q.adoc",
    },
    MarkerSpec {
        marker: "q3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/q.adoc",
    },
    MarkerSpec {
        marker: "q4",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/q.adoc",
    },
    MarkerSpec {
        marker: "qa",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qa.adoc",
    },
    MarkerSpec {
        marker: "qac",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Para],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/qac.adoc",
    },
    MarkerSpec {
        marker: "qc",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qc.adoc",
    },
    MarkerSpec {
        marker: "qd",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qd.adoc",
    },
    MarkerSpec {
        marker: "qm",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qm.adoc",
    },
    MarkerSpec {
        marker: "qm1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qm.adoc",
    },
    MarkerSpec {
        marker: "qm2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qm.adoc",
    },
    MarkerSpec {
        marker: "qm3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qm.adoc",
    },
    MarkerSpec {
        marker: "qr",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/qr.adoc",
    },
    MarkerSpec {
        marker: "qs",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Para],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/qs.adoc",
    },
    MarkerSpec {
        marker: "qt",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/qt.adoc",
    },
    MarkerSpec {
        marker: "qt-e",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/qt.adoc",
    },
    MarkerSpec {
        marker: "qt-s",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/qt.adoc",
    },
    MarkerSpec {
        marker: "r",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/r.adoc",
    },
    MarkerSpec {
        marker: "rb",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/rb.adoc",
    },
    MarkerSpec {
        marker: "ref",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
            SpecContext::CrossReference,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/ref.adoc",
    },
    MarkerSpec {
        marker: "rem",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/rem.adoc",
    },
    MarkerSpec {
        marker: "rq",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/rq.adoc",
    },
    MarkerSpec {
        marker: "s",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/s.adoc",
    },
    MarkerSpec {
        marker: "s1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/s.adoc",
    },
    MarkerSpec {
        marker: "s2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/s.adoc",
    },
    MarkerSpec {
        marker: "s3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/s.adoc",
    },
    MarkerSpec {
        marker: "s4",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/s.adoc",
    },
    MarkerSpec {
        marker: "sc",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/sc.adoc",
    },
    MarkerSpec {
        marker: "sd",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sd.adoc",
    },
    MarkerSpec {
        marker: "sd1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sd.adoc",
    },
    MarkerSpec {
        marker: "sd2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sd.adoc",
    },
    MarkerSpec {
        marker: "sd3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sd.adoc",
    },
    MarkerSpec {
        marker: "sig",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/sig.adoc",
    },
    MarkerSpec {
        marker: "sls",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/sls.adoc",
    },
    MarkerSpec {
        marker: "sp",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sp.adoc",
    },
    MarkerSpec {
        marker: "sr",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sr.adoc",
    },
    MarkerSpec {
        marker: "sts",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/sts.adoc",
    },
    MarkerSpec {
        marker: "sup",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/sup.adoc",
    },
    MarkerSpec {
        marker: "ta",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/ta.adoc",
    },
    MarkerSpec {
        marker: "tc",
        kind: SpecMarkerKind::TableCell,
        contexts: &[SpecContext::Table],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/tc.adoc",
    },
    MarkerSpec {
        marker: "tcc",
        kind: SpecMarkerKind::TableCell,
        contexts: &[SpecContext::Table],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/tcc.adoc",
    },
    MarkerSpec {
        marker: "tcr",
        kind: SpecMarkerKind::TableCell,
        contexts: &[SpecContext::Table],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/tcr.adoc",
    },
    MarkerSpec {
        marker: "th",
        kind: SpecMarkerKind::TableCell,
        contexts: &[SpecContext::Table],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/th.adoc",
    },
    MarkerSpec {
        marker: "thc",
        kind: SpecMarkerKind::TableCell,
        contexts: &[SpecContext::Table],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/thc.adoc",
    },
    MarkerSpec {
        marker: "thr",
        kind: SpecMarkerKind::TableCell,
        contexts: &[SpecContext::Table],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/thr.adoc",
    },
    MarkerSpec {
        marker: "tl",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/tl.adoc",
    },
    MarkerSpec {
        marker: "toc",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toc.adoc",
    },
    MarkerSpec {
        marker: "toc1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toc.adoc",
    },
    MarkerSpec {
        marker: "toc2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toc.adoc",
    },
    MarkerSpec {
        marker: "toc3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toc.adoc",
    },
    MarkerSpec {
        marker: "toca",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toca.adoc",
    },
    MarkerSpec {
        marker: "toca1",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toca.adoc",
    },
    MarkerSpec {
        marker: "toca2",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toca.adoc",
    },
    MarkerSpec {
        marker: "toca3",
        kind: SpecMarkerKind::Paragraph,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/toca.adoc",
    },
    MarkerSpec {
        marker: "tr",
        kind: SpecMarkerKind::TableRow,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/para/tr.adoc",
    },
    MarkerSpec {
        marker: "ts-s / ts-e",
        kind: SpecMarkerKind::Milestone,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/ms/ts.adoc",
    },
    MarkerSpec {
        marker: "usfm",
        kind: SpecMarkerKind::Header,
        contexts: &[SpecContext::BookHeaders],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/doc/usfm.adoc",
    },
    MarkerSpec {
        marker: "v",
        kind: SpecMarkerKind::Verse,
        contexts: &[
            SpecContext::Scripture,
            SpecContext::ChapterContent,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cv/v.adoc",
    },
    MarkerSpec {
        marker: "va",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Verse],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cv/va.adoc",
    },
    MarkerSpec {
        marker: "vid",
        kind: SpecMarkerKind::Milestone,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/ms/vid.adoc",
    },
    MarkerSpec {
        marker: "vid-e",
        kind: SpecMarkerKind::Milestone,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/ms/vid.adoc",
    },
    MarkerSpec {
        marker: "vid-s",
        kind: SpecMarkerKind::Milestone,
        contexts: &[SpecContext::ChapterContent],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/ms/vid.adoc",
    },
    MarkerSpec {
        marker: "vp",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::Verse],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/cv/vp.adoc",
    },
    MarkerSpec {
        marker: "w",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/w.adoc",
    },
    MarkerSpec {
        marker: "wa",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/wa.adoc",
    },
    MarkerSpec {
        marker: "wg",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/wg.adoc",
    },
    MarkerSpec {
        marker: "wh",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/wh.adoc",
    },
    MarkerSpec {
        marker: "wj",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/wj.adoc",
    },
    MarkerSpec {
        marker: "wl",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/wl.adoc",
    },
    MarkerSpec {
        marker: "x",
        kind: SpecMarkerKind::Note,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::ChapterContent,
            SpecContext::PeripheralContent,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/note/x.adoc",
    },
    MarkerSpec {
        marker: "xdc",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: true,
        source: "repos_to_compare/tcdocs-main/markers/char/xdc.adoc",
    },
    MarkerSpec {
        marker: "xk",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xk.adoc",
    },
    MarkerSpec {
        marker: "xnt",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xnt.adoc",
    },
    MarkerSpec {
        marker: "xo",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xo.adoc",
    },
    MarkerSpec {
        marker: "xop",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xop.adoc",
    },
    MarkerSpec {
        marker: "xot",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xot.adoc",
    },
    MarkerSpec {
        marker: "xq",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xq.adoc",
    },
    MarkerSpec {
        marker: "xt",
        kind: SpecMarkerKind::Character,
        contexts: &[
            SpecContext::BookTitles,
            SpecContext::BookIntroduction,
            SpecContext::BookIntroductionEndTitles,
            SpecContext::Section,
            SpecContext::Para,
            SpecContext::List,
            SpecContext::Table,
            SpecContext::Footnote,
            SpecContext::CrossReference,
        ],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xt.adoc",
    },
    MarkerSpec {
        marker: "xta",
        kind: SpecMarkerKind::Character,
        contexts: &[SpecContext::CrossReference],
        deprecated: false,
        source: "repos_to_compare/tcdocs-main/markers/char/xta.adoc",
    },
];
