//! Finding-section golden vectors: the Phase C JS decoder's future
//! conformance inputs, generated by this crate's own encoder rather than
//! hand-assembled — mirrors `token_goldens.rs` exactly, one section pair
//! (token + finding) per container instead of one.
//!
//! Each good vector is a full two-section container (`.bin`), its exact
//! source text (`.usfm`), and a manifest (`.json`) naming what it proves.
//! Each malformed vector is a `.bin` plus a manifest naming the exact
//! [`DecodeError`] it must produce.
//!
//! Regenerate with:
//!   cargo test -p usfm_onion_wire --lib finding_goldens::generate_finding_goldens -- --ignored
//!
//! [`finding_goldens_decode_and_match_lint`] and
//! [`malformed_finding_goldens_reject_with_the_recorded_error`] run on every
//! `cargo test` and fail if the checked-in fixtures drift from what the
//! encoder currently produces, or stop decoding/rejecting as recorded.

use std::fs;
use std::path::{Path, PathBuf};

use usfm_onion::lint::{LintCode, LintIssue, LintOptions, LintScope, MessageParams, lint_tokens};
use usfm_onion::parse::parse;
use usfm_onion::token::BookId;

use crate::error::DecodeError;
use crate::finding_codec::{decode_book, encode_book, issue_round_trips};

fn book(code: &str) -> BookId {
    BookId::from_str(code).expect("golden book code")
}

fn goldens_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("golden/finding")
}

struct GoodVector {
    name: &'static str,
    source: &'static str,
    proves: &'static str,
}

/// Builds the one hand-constructed issue this module needs: `finding_codec`'s
/// own unit tests already cover why `invalid-number-range` cannot come from a
/// real lint pass over any `Token<'a>` stream. Reused here (rather than
/// duplicated) so the golden's "extra issue" stays consistent with that
/// explanation.
fn hand_built_invalid_number_range(source: &str) -> LintIssue {
    use usfm_onion::LintableToken;
    let parsed = parse(source);
    let anchor = parsed
        .tokens
        .iter()
        .find(|token| token.kind() == usfm_onion::token::TokenKind::Number)
        .expect("golden source carries a verse number token");
    let params = MessageParams::from([
        ("found".to_string(), "4-2x".to_string()),
        ("verse".to_string(), "4".to_string()),
        ("marker".to_string(), "v".to_string()),
        ("context".to_string(), "numbering".to_string()),
    ]);
    LintIssue {
        code: LintCode::InvalidNumberRange,
        category: LintCode::InvalidNumberRange.category(),
        severity: LintCode::InvalidNumberRange.severity(),
        issue_type: LintCode::InvalidNumberRange.issue_type(),
        template: LintCode::InvalidNumberRange.template(),
        message: LintCode::InvalidNumberRange.render_message(&params),
        message_params: params,
        span: Some(anchor.span),
        related_span: None,
        token_id: anchor.id(),
        related_token_id: None,
        sid: anchor.sid.map(|sid| sid.to_string()),
        marker: Some("v".to_string()),
        fix: None,
        // `encode_book`'s own row placement resolves `token_id` strings, not
        // these fields (core-only, never read by the wire encoder) — a
        // sentinel is correct here, not just convenient.
        position: usfm_onion::lint::NO_TOKEN_POSITION,
        related_position: usfm_onion::lint::NO_TOKEN_POSITION,
    }
}

fn good_vectors() -> Vec<GoodVector> {
    vec![
        GoodVector {
            name: "several-codes",
            source: "\\id gen Genesis\n\\c 1\n\\p\n\\v 1 In the beginning\n\\v 1 duplicate\n",
            proves: "a small book producing several ordinary codes: empty-paragraph is absent here, but book-code-not-uppercase, duplicate-verse-number (related span), and verse-is-empty (catalog-ordinal marker) all fire together",
        },
        GoodVector {
            name: "related-span-unclosed-marker",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1 \\f + text\n",
            proves: "an unclosed \\f carries a related span pointing back at the opening marker, exercising the 16-byte related record",
        },
        GoodVector {
            name: "unknown-marker-anchored",
            source: "\\zzz unknown marker\n",
            proves: "unknown-marker's marker is recovered from the anchored token's own descriptor (MarkerRef::AnchoredToken), zero marker-ref bytes",
        },
        GoodVector {
            name: "whitespace-fix-patch",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1 should have error\\p\\nd testing \\nd*\n",
            proves: "one token carrying two different fixes (missing-whitespace-before-marker and missing-tag-end-delimiter-after-marker), so the patch table stores two records, their rows, and the fix strings interned in the finding-section dictionary",
        },
        GoodVector {
            name: "book-code-not-uppercase-remedy",
            source: "\\id php Philippians\n",
            proves: "book-code-not-uppercase's uppercase remedy is a message-parameter value absent from the source and not a catalog marker — proof field 7/8 (message payload table) is load-bearing, not cosmetic",
        },
    ]
}

/// One malformed vector: `base` corrupted by `corrupt`, expected to reject
/// with exactly `expected`.
struct MalformedVector {
    name: &'static str,
    base: &'static str,
    corrupt: fn(&mut Vec<u8>),
    expected: DecodeError,
    proves: &'static str,
}

fn truncate_below_header(bytes: &mut Vec<u8>) {
    bytes.truncate(20);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn flip_magic(bytes: &mut Vec<u8>) {
    bytes[0] ^= 0xff;
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn wrong_version(bytes: &mut Vec<u8>) {
    bytes[4..6].copy_from_slice(&9999u16.to_le_bytes());
}

/// Every TOC entry's `(offset, byte_len)`, read before any corruption so a
/// later edit can still locate section boundaries.
pub(crate) fn section_bounds(bytes: &[u8]) -> Vec<(usize, usize)> {
    let container =
        crate::container::read_container_unchecked(bytes).expect("base vector is well-formed");
    container
        .toc()
        .iter()
        .map(|entry| (entry.offset as usize, entry.byte_len as usize))
        .collect()
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn checksum_mismatch(bytes: &mut Vec<u8>) {
    // Flip a content byte inside the finding section's payload (past its own
    // 64-byte header) without restamping either checksum.
    let (offset, _) = section_bounds(bytes)[1];
    bytes[offset + 64] ^= 0xff;
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn out_of_range_token_idx(bytes: &mut Vec<u8>) {
    let (offset, _) = section_bounds(bytes)[1];
    let container = crate::container::read_container(bytes).expect("base vector is well-formed");
    let section = container.section(1).expect("finding section").unwrap();
    let field = section
        .field(crate::schema::finding_field::COMMON_ROW)
        .expect("common row field present");
    let row_offset = field.bytes.as_ptr() as usize - bytes.as_ptr() as usize;
    // Row 0's token_idx, one past any token index this tiny vector could have.
    bytes[row_offset..row_offset + 4].copy_from_slice(&0xfffe_fffeu32.to_le_bytes());
    restamp_section(bytes, offset);
    restamp_container(bytes);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn nonzero_related_reserved(bytes: &mut Vec<u8>) {
    let (offset, _) = section_bounds(bytes)[1];
    let container = crate::container::read_container(bytes).expect("base vector is well-formed");
    let section = container.section(1).expect("finding section").unwrap();
    let field = section
        .field(crate::schema::finding_field::RELATED_TOKEN_IDX)
        .expect("related field present on this base vector");
    let related_offset = field.bytes.as_ptr() as usize - bytes.as_ptr() as usize;
    bytes[related_offset + 12] = 1; // reserved word, must be zero
    restamp_section(bytes, offset);
    restamp_container(bytes);
}

/// Recomputes one section's own integrity checksum in place.
pub(crate) fn restamp_section(bytes: &mut [u8], section_offset: usize) {
    use crate::schema::SECTION_CHECKSUM_OFFSET;
    // Section header layout (64 bytes): magic(4) format_version(2)
    // rules_version(2) kind(1) flags(1) book(3) reserved(3) record_count(4)
    // directory_count(2) directory_entry_len(2) source_hash(8) = 32 bytes in,
    // then section_len:u64 at [32..40), checksum:u64 at
    // [SECTION_CHECKSUM_OFFSET..SECTION_CHECKSUM_OFFSET+8).
    let section_len = u64::from_le_bytes(
        bytes[section_offset + 32..section_offset + SECTION_CHECKSUM_OFFSET]
            .try_into()
            .unwrap(),
    ) as usize;
    let section_end = section_offset + section_len;
    let checksum_start = section_offset + SECTION_CHECKSUM_OFFSET;
    bytes[checksum_start..checksum_start + 8].copy_from_slice(&[0u8; 8]);
    let checksum = crate::primitives::integrity_checksum(
        &bytes[section_offset..section_end],
        SECTION_CHECKSUM_OFFSET,
    );
    bytes[checksum_start..checksum_start + 8].copy_from_slice(&checksum.to_le_bytes());
}

/// Recomputes the container-wide integrity checksum in place.
pub(crate) fn restamp_container(bytes: &mut [u8]) {
    use crate::schema::CONTAINER_CHECKSUM_OFFSET;
    bytes[CONTAINER_CHECKSUM_OFFSET..CONTAINER_CHECKSUM_OFFSET + 8].copy_from_slice(&[0u8; 8]);
    let checksum = crate::primitives::integrity_checksum(bytes, CONTAINER_CHECKSUM_OFFSET);
    bytes[CONTAINER_CHECKSUM_OFFSET..CONTAINER_CHECKSUM_OFFSET + 8]
        .copy_from_slice(&checksum.to_le_bytes());
}

/// The absolute byte offset of one finding-section field's payload.
fn field_offset(bytes: &[u8], field_id: u16) -> usize {
    let container = crate::container::read_container(bytes).expect("base vector is well-formed");
    let section = container.section(1).expect("finding section").unwrap();
    let field = section
        .field(field_id)
        .expect("base vector carries this field");
    field.bytes.as_ptr() as usize - bytes.as_ptr() as usize
}

/// Rewrites the first patch row's bytes, then restamps both checksums so what is
/// under test is the patch table's own validation rather than the checksum.
fn corrupt_first_patch_row(bytes: &mut [u8], edit: impl FnOnce(&mut [u8])) {
    let (offset, _) = section_bounds(bytes)[1];
    // The row array follows the fixed-size records, whose count is the field's
    // own element count.
    let table = field_offset(bytes, crate::schema::finding_field::PATCH_TABLE);
    let records = {
        let container = crate::container::read_container(bytes).expect("well-formed");
        let section = container.section(1).unwrap().unwrap();
        section
            .field(crate::schema::finding_field::PATCH_TABLE)
            .unwrap()
            .count as usize
    };
    let row = table + records * 24;
    edit(&mut bytes[row..row + 20]);
    restamp_section(bytes, offset);
    restamp_container(bytes);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn unknown_patch_op(bytes: &mut Vec<u8>) {
    corrupt_first_patch_row(bytes, |row| row[0] = 9);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn nonzero_patch_row_reserved(bytes: &mut Vec<u8>) {
    corrupt_first_patch_row(bytes, |row| row[2] = 1);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn patch_row_position_out_of_range(bytes: &mut Vec<u8>) {
    corrupt_first_patch_row(bytes, |row| {
        row[4..8].copy_from_slice(&0xfffe_fffeu32.to_le_bytes())
    });
}

/// Empties the first patch record's row run and hands its row to the second, so
/// the record/row partition still adds up and the only rule broken is "a fix
/// edits something". The writer cannot produce this shape at all, which is why
/// the vector has to be built by corrupting one that it can.
#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn zero_row_patch_record(bytes: &mut Vec<u8>) {
    let (offset, _) = section_bounds(bytes)[1];
    let table = field_offset(bytes, crate::schema::finding_field::PATCH_TABLE);
    // Record 0: keep first_row, zero the count. Record 1: absorb both rows.
    bytes[table + 4..table + 8].copy_from_slice(&0u32.to_le_bytes());
    bytes[table + 24..table + 28].copy_from_slice(&0u32.to_le_bytes());
    bytes[table + 28..table + 32].copy_from_slice(&2u32.to_le_bytes());
    restamp_section(bytes, offset);
    restamp_container(bytes);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn patch_index_column_not_dense(bytes: &mut Vec<u8>) {
    let (offset, _) = section_bounds(bytes)[1];
    let column = field_offset(bytes, crate::schema::finding_field::PATCH_ID);
    // Every non-sentinel entry must be the next dense index; find the first real
    // one and skip a number.
    for row in 0.. {
        let at = column + row * 4;
        let value = u32::from_le_bytes(bytes[at..at + 4].try_into().unwrap());
        if value != u32::MAX {
            bytes[at..at + 4].copy_from_slice(&(value + 1).to_le_bytes());
            break;
        }
    }
    restamp_section(bytes, offset);
    restamp_container(bytes);
}

fn malformed_vectors() -> Vec<MalformedVector> {
    vec![
        MalformedVector {
            name: "truncated",
            base: "several-codes",
            corrupt: truncate_below_header,
            expected: DecodeError::Truncated,
            proves: "a buffer chopped mid-container rejects rather than reading past its end",
        },
        MalformedVector {
            name: "bad-magic",
            base: "several-codes",
            corrupt: flip_magic,
            expected: DecodeError::BadMagic,
            proves: "a buffer not starting with the container magic rejects immediately",
        },
        MalformedVector {
            name: "wrong-version",
            base: "several-codes",
            corrupt: wrong_version,
            expected: DecodeError::UnsupportedVersion { found: 9999 },
            proves: "a format_version this build does not implement rejects rather than misinterpreting the layout",
        },
        MalformedVector {
            name: "checksum-mismatch",
            base: "several-codes",
            corrupt: checksum_mismatch,
            expected: DecodeError::ChecksumMismatch,
            proves: "a content byte changed inside the finding section without updating its checksum rejects",
        },
        MalformedVector {
            name: "out-of-range-token-idx",
            base: "several-codes",
            corrupt: out_of_range_token_idx,
            expected: DecodeError::InvalidSection,
            proves: "a common row's token_idx naming no token in the paired section rejects rather than reading out of bounds",
        },
        MalformedVector {
            name: "unknown-patch-op",
            base: "whitespace-fix-patch",
            corrupt: unknown_patch_op,
            expected: DecodeError::InvalidDiscriminant,
            proves: "a patch row's op byte outside the frozen insert/replace/delete set rejects rather than defaulting to one of them",
        },
        MalformedVector {
            name: "nonzero-patch-row-reserved",
            base: "whitespace-fix-patch",
            corrupt: nonzero_patch_row_reserved,
            expected: DecodeError::InvalidSection,
            proves: "a patch row's reserved half-word must be zero; a nonzero value is a future producer's field this build cannot honour",
        },
        MalformedVector {
            name: "patch-row-position-out-of-range",
            base: "whitespace-fix-patch",
            corrupt: patch_row_position_out_of_range,
            expected: DecodeError::InvalidSection,
            proves: "a patch row naming a token position the paired token section does not have rejects rather than resolving a target id out of bounds",
        },
        MalformedVector {
            name: "zero-row-patch-record",
            base: "whitespace-fix-patch",
            corrupt: zero_row_patch_record,
            expected: DecodeError::InvalidSection,
            proves: "a patch record with an empty row run rejects: a fix that edits nothing is not a fix, and a zero-row run cannot be told apart from the next record's run — the writer refuses to produce this shape, so the decoder must refuse to read it",
        },
        MalformedVector {
            name: "patch-index-column-not-dense",
            base: "whitespace-fix-patch",
            corrupt: patch_index_column_not_dense,
            expected: DecodeError::InvalidSection,
            proves: "the patch addressing column is dense and ascending; a skipped index leaves a record no finding claims and rejects",
        },
        MalformedVector {
            name: "nonzero-related-reserved",
            base: "related-span-unclosed-marker",
            corrupt: nonzero_related_reserved,
            expected: DecodeError::InvalidSection,
            proves: "the 16-byte related record's trailing reserved word must be zero; a nonzero value rejects",
        },
    ]
}

fn encode_good(vector: &GoodVector) -> (String, Vec<u8>) {
    let parsed = parse(vector.source);
    let mut issues = lint_tokens(&parsed.tokens, LintOptions::scoped(LintScope::Book)).issues;
    if vector.name == "several-codes" {
        issues.push(hand_built_invalid_number_range(vector.source));
    }
    let bytes = encode_book(book("GEN"), vector.source, &parsed.tokens, &issues)
        .expect("golden book encodes");
    (vector.source.to_string(), bytes)
}

fn manifest_json(fields: &[(&str, String)]) -> String {
    let mut out = String::from("{\n");
    for (index, (key, value)) in fields.iter().enumerate() {
        let sep = if index + 1 == fields.len() { "" } else { "," };
        out.push_str(&format!("  \"{key}\": {value}{sep}\n"));
    }
    out.push_str("}\n");
    out
}

fn json_string(value: &str) -> String {
    format!("{value:?}")
}

/// Regenerates every checked-in fixture under `golden/finding/`. `#[ignore]`d
/// like the corpus gates: run explicitly, never implicitly blessed.
#[test]
#[ignore = "regenerates checked-in golden fixtures; run explicitly"]
fn generate_finding_goldens() {
    let dir = goldens_dir();
    fs::create_dir_all(&dir).expect("create golden/finding");

    for vector in good_vectors() {
        let (source, bytes) = encode_good(&vector);
        fs::write(dir.join(format!("{}.bin", vector.name)), &bytes).unwrap();
        fs::write(dir.join(format!("{}.usfm", vector.name)), &source).unwrap();
        let manifest = manifest_json(&[
            ("name", json_string(vector.name)),
            ("kind", json_string("good")),
            ("proves", json_string(vector.proves)),
        ]);
        fs::write(dir.join(format!("{}.json", vector.name)), manifest).unwrap();
    }

    let good = good_vectors();
    for vector in malformed_vectors() {
        let base = good
            .iter()
            .find(|good| good.name == vector.base)
            .unwrap_or_else(|| panic!("malformed vector {} names a real base", vector.name));
        let (_, mut bytes) = encode_good(base);
        (vector.corrupt)(&mut bytes);
        fs::write(dir.join(format!("{}.bin", vector.name)), &bytes).unwrap();
        let manifest = manifest_json(&[
            ("name", json_string(vector.name)),
            ("kind", json_string("malformed")),
            ("base", json_string(vector.base)),
            (
                "expectedError",
                json_string(&format!("{:?}", vector.expected)),
            ),
            ("proves", json_string(vector.proves)),
        ]);
        fs::write(dir.join(format!("{}.json", vector.name)), manifest).unwrap();
    }

    println!(
        "wrote {} good + {} malformed vectors to {:?}",
        good_vectors().len(),
        malformed_vectors().len(),
        dir
    );
}

/// Runs on every `cargo test`: decodes each checked-in good vector and
/// asserts every issue round-trips against a fresh lint of its own source.
#[test]
fn finding_goldens_decode_and_match_lint() {
    let dir = goldens_dir();

    for vector in good_vectors() {
        let bin_path = dir.join(format!("{}.bin", vector.name));
        let source_path = dir.join(format!("{}.usfm", vector.name));
        let bytes = fs::read(&bin_path)
            .unwrap_or_else(|e| panic!("read {bin_path:?}: {e} (run generate_finding_goldens)"));
        let committed_source = fs::read_to_string(&source_path)
            .unwrap_or_else(|e| panic!("read {source_path:?}: {e}"));

        let (expected_source, expected_bytes) = encode_good(&vector);
        assert_eq!(
            committed_source, expected_source,
            "{}.usfm is stale — regenerate with generate_finding_goldens",
            vector.name
        );
        assert_eq!(
            bytes, expected_bytes,
            "{}.bin is stale — regenerate with generate_finding_goldens",
            vector.name
        );

        let parsed = parse(&committed_source);
        let mut original = lint_tokens(&parsed.tokens, LintOptions::scoped(LintScope::Book)).issues;
        if vector.name == "several-codes" {
            original.push(hand_built_invalid_number_range(&committed_source));
        }
        crate::finding_codec::canonical_order_for_tokens(&mut original, &parsed.tokens);

        let decoded = decode_book(&bytes, &committed_source)
            .unwrap_or_else(|e| panic!("{} decodes: {e:?}", vector.name));
        assert_eq!(
            original.len(),
            decoded.len(),
            "{} finding count",
            vector.name
        );
        for (index, (original, decoded)) in original.iter().zip(&decoded).enumerate() {
            assert!(
                issue_round_trips(original, decoded),
                "{} finding {index} mismatch:\n  original: {original:?}\n  decoded:  {decoded:?}",
                vector.name
            );
        }
    }
}

/// Runs on every `cargo test`: decodes each checked-in malformed vector and
/// asserts it rejects with exactly the recorded `DecodeError`.
#[test]
fn malformed_finding_goldens_reject_with_the_recorded_error() {
    let dir = goldens_dir();
    let good = good_vectors();

    for vector in malformed_vectors() {
        let bin_path = dir.join(format!("{}.bin", vector.name));
        let bytes = fs::read(&bin_path)
            .unwrap_or_else(|e| panic!("read {bin_path:?}: {e} (run generate_finding_goldens)"));

        let base = good.iter().find(|good| good.name == vector.base).unwrap();
        let (base_source, mut expected_bytes) = encode_good(base);
        (vector.corrupt)(&mut expected_bytes);
        assert_eq!(
            bytes, expected_bytes,
            "{}.bin is stale — regenerate with generate_finding_goldens",
            vector.name
        );

        let result = decode_book(&bytes, &base_source);
        assert_eq!(
            result.err(),
            Some(vector.expected),
            "{} must reject with the recorded error",
            vector.name
        );
    }
}
