//! Token-section golden vectors: the Phase B JS decoder's future conformance
//! inputs, generated by this crate's own encoder rather than hand-assembled.
//!
//! Each good vector is a full one-section container (`.bin`), its exact
//! source text (`.usfm`), and a manifest (`.json`) naming what it proves.
//! Each malformed vector is a `.bin` plus a manifest naming the exact
//! [`DecodeError`] it must produce.
//!
//! Regenerate with:
//!   cargo test -p usfm_onion_wire --lib token_goldens::generate_token_goldens -- --ignored
//!
//! [`token_goldens_decode_and_match_parse`] and
//! [`malformed_token_goldens_reject_with_the_recorded_error`] run on every
//! `cargo test` and fail if the checked-in fixtures drift from what the
//! encoder currently produces, or stop decoding/rejecting as recorded.

use std::fs;
use std::path::{Path, PathBuf};

use usfm_onion::parse::parse;
use usfm_onion::token::{BookId, OwnedToken, TokenKind};

use crate::container::{read_container, write_container};
use crate::error::DecodeError;
use crate::token_codec::{
    decode_token_section, encode_owned_token_section, encode_token_section,
    encode_token_section_with_ids,
};

const SNAPSHOT_ID: u64 = 1;

fn book(code: &str) -> BookId {
    BookId::from_str(code).expect("golden book code")
}

fn goldens_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("golden/token")
}

/// GUID-ish ids, the shape a live editor supplies — same construction as the
/// narrow explicit-id tests in `token_codec_tests.rs`.
fn guid_ids(count: usize) -> Vec<String> {
    (0..count)
        .map(|index| format!("7f3c9a{index:04x}-b21e-4d0f-9c8a-{index:012x}"))
        .collect()
}

enum Encoding {
    /// Parsed source, positional ids (the ordinary cold-load path).
    Parsed,
    /// Parsed source, explicit opaque ids (the live-editor path).
    ExplicitIds,
    /// Owned tokens, serialize-then-encode (the braid-snapshot path).
    Owned,
}

struct GoodVector {
    name: &'static str,
    source: &'static str,
    encoding: Encoding,
    proves: &'static str,
    /// True for a vector whose packed sid cannot represent its full bridge
    /// width and degrades to `AnchorOnly`, storing just the anchor. Always
    /// `false` in the current vector set: v2's delta byte is unshared with
    /// the fidelity bit (see `crate::schema::layout::packed_sid`) and covers
    /// every width `Sid` itself allows (0-255), so there is no longer a
    /// bridge that degrades on width alone — v1's >127-verse case is
    /// `sid-fidelity-wide-bridge-stays-exact` below instead. Kept as a field
    /// (not removed) so a future ceiling change has somewhere to hang a
    /// lossy vector again. When true, the token-equality check compares
    /// everything except `sid.verse_end()`.
    sid_range_end_lossy: bool,
}

fn good_vectors() -> Vec<GoodVector> {
    vec![
        GoodVector {
            name: "all-token-kinds",
            source: "\\id GEN Some Book\n\\c 1\n\\p text // more\n\\w word|strong=\"H1\"\\w* and \\add \\+nd Lord\\+nd*\\add*\n\\qt-s |x=\"y\"\\*inside\\qt-e\\*\n\\v 1-2 bridge\n",
            encoding: Encoding::Parsed,
            proves: "every TokenKind (Newline, OptBreak, Marker, EndMarker, Milestone, MilestoneEnd, BookCode, Number, Text) with legal payloads, encoded with positional ids",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "explicit-ids",
            source: "\\id GEN\n\\c 1\n\\p \\w a|k=\"v\"\\w* b\n\\v 1-2 text\n",
            encoding: Encoding::ExplicitIds,
            proves: "opaque caller-supplied stable ids round-trip via the id column + dictionary, flag clear",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "unknown-marker",
            source: "\\zzz unknown marker\n",
            encoding: Encoding::Parsed,
            proves: "a marker absent from the catalog keeps its name via the descriptor dictionary, with all-None catalog metadata",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "sid-fidelity-exact-bare",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1 a\n",
            encoding: Encoding::Parsed,
            proves: "a bare verse number is Exact fidelity",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "sid-fidelity-exact-bridge",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1-2 a\n",
            encoding: Encoding::Parsed,
            proves: "a simple two-number bridge spells its whole designator: Exact fidelity",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "sid-fidelity-sequence-anchor-only",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1,3 a\n",
            encoding: Encoding::Parsed,
            proves: "a sequence's anchor (verse 1) cannot distinguish it from a bare verse: AnchorOnly fidelity",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "sid-fidelity-suffix-anchor-only",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1a a\n",
            encoding: Encoding::Parsed,
            proves: "a suffixed verse is identical to an unsuffixed one in Sid and NumberRangeKind: AnchorOnly fidelity",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "sid-fidelity-wide-bridge-stays-exact",
            source: "\\id GEN\n\\c 1\n\\p\n\\v 1-255 a\n",
            encoding: Encoding::Parsed,
            proves: "v2's unshared delta byte covers a bridge up to Sid's own 255-verse ceiling as Exact — the v1 7-bit-delta ceiling that degraded this to AnchorOnly is gone",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "attributes-none-default-and-empty",
            source: "\\p \\w grace\\w* \\w grace|H1234\\w* \\w grace|\\w*\n",
            encoding: Encoding::Parsed,
            proves: "three attribute-list shapes on the same marker: absent (no `|` at all), default-attribute shorthand (empty key), and an explicit present-but-empty list",
            sid_range_end_lossy: false,
        },
        GoodVector {
            name: "attribute-offset-remembered",
            source: "\\p \\w grace|lemma=\"grace\" x-y=\"z\"\\w* and \\add more\\add*\n",
            encoding: Encoding::Owned,
            proves: "an owned token remembers its attribute list's offset from its own end, so the derived source is byte-identical even though the list is emitted at the marker's closer, not adjacent to its span",
            sid_range_end_lossy: false,
        },
    ]
}

/// One malformed vector: `base` corrupted by `corrupt`, expected to reject
/// with exactly `expected`. Built from a good vector's own bytes so the
/// starting point is always something the encoder actually produced.
struct MalformedVector {
    name: &'static str,
    base: &'static str,
    corrupt: fn(&mut Vec<u8>),
    expected: DecodeError,
    proves: &'static str,
}

fn truncate_below_header(bytes: &mut Vec<u8>) {
    // Shorter than the 48-byte container header, so the failure is the
    // header-length check itself, before any checksum is even read — a
    // half-length truncation instead lands on `ChecksumMismatch` (the
    // checksum covers the whole original length), which is a real but
    // different rejection this vector is not naming.
    bytes.truncate(20);
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn flip_magic(bytes: &mut Vec<u8>) {
    bytes[0] ^= 0xff;
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn wrong_version(bytes: &mut Vec<u8>) {
    // Container header offset 4..6 is `format_version` (see
    // `read_container_header`).
    bytes[4..6].copy_from_slice(&9999u16.to_le_bytes());
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn checksum_mismatch(bytes: &mut Vec<u8>) {
    // Flip a content byte inside the section payload (past the 48-byte
    // container header + 32-byte TOC entry) without restamping either
    // checksum.
    let index = 48 + 32 + 8;
    bytes[index] ^= 0xff;
}

#[allow(clippy::ptr_arg)] // shares a `fn(&mut Vec<u8>)` pointer type with truncate_below_header, which needs Vec::truncate
fn out_of_range_sid_index(bytes: &mut Vec<u8>) {
    let container = read_container(bytes).expect("base vector is well-formed");
    let section = container
        .section(0)
        .expect("one section")
        .expect("section decodes");
    let field = section
        .field(crate::schema::token_field::SID_INDEX)
        .expect("sid_index field present");
    let offset = field.bytes.as_ptr() as usize - bytes.as_ptr() as usize;
    // Row 0's sid_index, set one past the sentinel-adjacent legal range: not
    // `INDEX_NONE_U16` (which means "no sid"), and larger than any dictionary
    // this tiny vector could have built.
    bytes[offset..offset + 2].copy_from_slice(&0xfffeu16.to_le_bytes());
    restamp(bytes);
}

/// Recomputes the section and container integrity checksums after an edit —
/// copied from `token_codec_tests::restamp` (test-only code, not worth a
/// third copy via a shared helper module for two call sites).
fn restamp(bytes: &mut [u8]) {
    let section_offset = u64::from_le_bytes(bytes[56..64].try_into().unwrap()) as usize;
    let section_len = u64::from_le_bytes(bytes[64..72].try_into().unwrap()) as usize;
    let section_end = section_offset + section_len;
    bytes[section_offset + 40..section_offset + 48].copy_from_slice(&[0u8; 8]);
    let section_checksum =
        crate::primitives::integrity_checksum(&bytes[section_offset..section_end], 40);
    bytes[section_offset + 40..section_offset + 48]
        .copy_from_slice(&section_checksum.to_le_bytes());
    bytes[24..32].copy_from_slice(&[0u8; 8]);
    let container_checksum = crate::primitives::integrity_checksum(bytes, 24);
    bytes[24..32].copy_from_slice(&container_checksum.to_le_bytes());
}

fn malformed_vectors() -> Vec<MalformedVector> {
    vec![
        MalformedVector {
            name: "truncated",
            base: "all-token-kinds",
            corrupt: truncate_below_header,
            expected: DecodeError::Truncated,
            proves: "a buffer chopped mid-container rejects rather than reading past its end",
        },
        MalformedVector {
            name: "bad-magic",
            base: "all-token-kinds",
            corrupt: flip_magic,
            expected: DecodeError::BadMagic,
            proves: "a buffer not starting with the container magic rejects immediately",
        },
        MalformedVector {
            name: "wrong-version",
            base: "all-token-kinds",
            corrupt: wrong_version,
            expected: DecodeError::UnsupportedVersion { found: 9999 },
            proves: "a format_version this build does not implement rejects rather than misinterpreting the layout",
        },
        MalformedVector {
            name: "checksum-mismatch",
            base: "all-token-kinds",
            corrupt: checksum_mismatch,
            expected: DecodeError::ChecksumMismatch,
            proves: "a content byte changed without updating the integrity checksum rejects",
        },
        MalformedVector {
            name: "out-of-range-index",
            base: "explicit-ids",
            corrupt: out_of_range_sid_index,
            expected: DecodeError::InvalidSection,
            proves: "an index column value naming no dictionary entry (and not the none-sentinel) rejects rather than reading out of bounds",
        },
    ]
}

fn encode_good(vector: &GoodVector) -> (String, Vec<u8>) {
    match vector.encoding {
        Encoding::Parsed => {
            let parsed = parse(vector.source);
            let buffers = encode_token_section(book("GEN"), vector.source, &parsed.tokens)
                .expect("parsed tokens encode");
            (
                vector.source.to_string(),
                write_container(SNAPSHOT_ID, &[buffers.payload()]).expect("section lays out"),
            )
        }
        Encoding::ExplicitIds => {
            let parsed = parse(vector.source);
            let ids = guid_ids(parsed.tokens.len());
            let borrowed: Vec<&str> = ids.iter().map(String::as_str).collect();
            let buffers = encode_token_section_with_ids(
                book("GEN"),
                vector.source,
                &parsed.tokens,
                Some(&borrowed),
            )
            .expect("explicit ids encode");
            (
                vector.source.to_string(),
                write_container(SNAPSHOT_ID, &[buffers.payload()]).expect("section lays out"),
            )
        }
        Encoding::Owned => {
            let parsed = parse(vector.source);
            let owned: Vec<_> = parsed.tokens.iter().map(OwnedToken::from_parsed).collect();
            let (derived, buffers) =
                encode_owned_token_section(book("GEN"), &owned).expect("owned tokens encode");
            (
                derived,
                write_container(SNAPSHOT_ID, &[buffers.payload()]).expect("section lays out"),
            )
        }
    }
}

fn manifest_json(fields: &[(&str, String)]) -> String {
    let mut out = String::from("{\n");
    for (index, (key, value)) in fields.iter().enumerate() {
        let sep = if index + 1 == fields.len() { "" } else { "," };
        out.push_str(&format!("  \"{key}\": {value}{sep}\n"));
    }
    out.push_str("}\n");
    out
}

fn json_string(value: &str) -> String {
    format!("{value:?}")
}

/// Regenerates every checked-in fixture under `golden/token/`. `#[ignore]`d
/// like the corpus gates: run explicitly, never implicitly blessed.
#[test]
#[ignore = "regenerates checked-in golden fixtures; run explicitly"]
fn generate_token_goldens() {
    let dir = goldens_dir();
    fs::create_dir_all(&dir).expect("create golden/token");

    for vector in good_vectors() {
        let (source, bytes) = encode_good(&vector);
        fs::write(dir.join(format!("{}.bin", vector.name)), &bytes).unwrap();
        fs::write(dir.join(format!("{}.usfm", vector.name)), &source).unwrap();
        let manifest = manifest_json(&[
            ("name", json_string(vector.name)),
            ("kind", json_string("good")),
            ("proves", json_string(vector.proves)),
        ]);
        fs::write(dir.join(format!("{}.json", vector.name)), manifest).unwrap();
    }

    let good = good_vectors();
    for vector in malformed_vectors() {
        let base = good
            .iter()
            .find(|good| good.name == vector.base)
            .unwrap_or_else(|| panic!("malformed vector {} names a real base", vector.name));
        let (_, mut bytes) = encode_good(base);
        (vector.corrupt)(&mut bytes);
        fs::write(dir.join(format!("{}.bin", vector.name)), &bytes).unwrap();
        let manifest = manifest_json(&[
            ("name", json_string(vector.name)),
            ("kind", json_string("malformed")),
            ("base", json_string(vector.base)),
            (
                "expectedError",
                json_string(&format!("{:?}", vector.expected)),
            ),
            ("proves", json_string(vector.proves)),
        ]);
        fs::write(dir.join(format!("{}.json", vector.name)), manifest).unwrap();
    }

    println!(
        "wrote {} good + {} malformed vectors to {:?}",
        good_vectors().len(),
        malformed_vectors().len(),
        dir
    );
}

/// Runs on every `cargo test`: decodes each checked-in good vector and
/// asserts semantic equality with a fresh `parse` of its own source.
#[test]
fn token_goldens_decode_and_match_parse() {
    let dir = goldens_dir();
    let mut seen_kinds = Vec::new();

    for vector in good_vectors() {
        let bin_path = dir.join(format!("{}.bin", vector.name));
        let source_path = dir.join(format!("{}.usfm", vector.name));
        let bytes = fs::read(&bin_path)
            .unwrap_or_else(|e| panic!("read {bin_path:?}: {e} (run generate_token_goldens)"));
        let committed_source = fs::read_to_string(&source_path)
            .unwrap_or_else(|e| panic!("read {source_path:?}: {e}"));

        let (expected_source, _) = encode_good(&vector);
        assert_eq!(
            committed_source, expected_source,
            "{}.usfm is stale — regenerate with generate_token_goldens",
            vector.name
        );
        let (_, expected_bytes) = encode_good(&vector);
        assert_eq!(
            bytes, expected_bytes,
            "{}.bin is stale — regenerate with generate_token_goldens",
            vector.name
        );

        let container = read_container(&bytes).expect("golden container decodes");
        let section = container
            .section(0)
            .expect("one section")
            .expect("section decodes");
        let decoded = decode_token_section(&section, &committed_source)
            .expect("token section decodes")
            .tokens;
        let expected = parse(&committed_source).tokens;
        assert_eq!(decoded.len(), expected.len(), "{} token count", vector.name);
        for (index, (decoded, expected)) in decoded.iter().zip(&expected).enumerate() {
            if vector.sid_range_end_lossy {
                // The packed sid format cannot represent this range at all
                // (AnchorOnly fidelity), so the wire round-trip legitimately
                // drops `verse_end`. Compare everything else, including the
                // anchor's own book/chapter/verse.
                let mut adjusted = decoded.clone();
                adjusted.sid = expected
                    .sid
                    .map(|sid| usfm_onion::token::Sid::new(sid.book, sid.chapter, sid.verse));
                let mut expected_anchor_only = expected.clone();
                expected_anchor_only.sid = expected
                    .sid
                    .map(|sid| usfm_onion::token::Sid::new(sid.book, sid.chapter, sid.verse));
                assert_eq!(
                    adjusted, expected_anchor_only,
                    "{} token {index} (sid range end intentionally dropped)",
                    vector.name
                );
            } else {
                assert_eq!(decoded, expected, "{} token {index}", vector.name);
            }
            seen_kinds.push(decoded.kind());
        }
    }

    // The "all-token-kinds" vector's name is a promise; prove it rather than
    // trusting the fixture's own docstring.
    for kind in [
        TokenKind::Newline,
        TokenKind::OptBreak,
        TokenKind::Marker,
        TokenKind::EndMarker,
        TokenKind::Milestone,
        TokenKind::MilestoneEnd,
        TokenKind::BookCode,
        TokenKind::Number,
        TokenKind::Text,
    ] {
        assert!(
            seen_kinds.contains(&kind),
            "no golden vector produced a {kind:?} token"
        );
    }
}

/// Runs on every `cargo test`: decodes each checked-in malformed vector and
/// asserts it rejects with exactly the recorded `DecodeError`.
#[test]
fn malformed_token_goldens_reject_with_the_recorded_error() {
    let dir = goldens_dir();
    let good = good_vectors();

    for vector in malformed_vectors() {
        let bin_path = dir.join(format!("{}.bin", vector.name));
        let bytes = fs::read(&bin_path)
            .unwrap_or_else(|e| panic!("read {bin_path:?}: {e} (run generate_token_goldens)"));

        let base = good.iter().find(|good| good.name == vector.base).unwrap();
        let (_, mut expected_bytes) = encode_good(base);
        (vector.corrupt)(&mut expected_bytes);
        assert_eq!(
            bytes, expected_bytes,
            "{}.bin is stale — regenerate with generate_token_goldens",
            vector.name
        );

        // Some corruptions (magic, version) fail inside `read_container`
        // itself; others (checksum, out-of-range index) pass the container
        // check and fail inside the section/token decode, which checks the
        // supplied source's length/hash before anything else — so the base
        // vector's own source must be supplied for those to reach the actual
        // failure being tested, not an earlier `SourceLengthMismatch`.
        let result = read_container(&bytes).and_then(|container| {
            let section = container.section(0).ok_or(DecodeError::InvalidToc)??;
            decode_token_section(&section, base.source).map(|_| ())
        });
        assert_eq!(
            result.err(),
            Some(vector.expected),
            "{} must reject with the recorded error",
            vector.name
        );
    }
}
