// Node-driven wasm bench harness.
//
// Mirrors `benches/operations.rs` (the native criterion bench): one
// representative book (en_ulb/43-LUK.usfm), one operation at a time,
// measuring elapsed time and bytes/sec. Emits a markdown table whose
// columns parallel `BENCH_RESULTS.md` so wasm vs. native throughput is
// directly comparable.
//
// Usage:
//   node --experimental-wasm-modules benches/wasm/run.mjs              # bundler target
//   node --experimental-wasm-modules benches/wasm/run.mjs web          # web target
//   BENCH_OUT=BENCH_RESULTS_WASM.md node ... benches/wasm/run.mjs      # write to file
//
// Criterion's defaults are 100 samples × 5s wall clock. For wasm we
// keep it lighter so a run finishes in a minute or two: ITERATIONS env
// var (default 50) sets per-op iteration count, with a 3-iteration
// warm-up first.

import { performance } from "node:perf_hooks";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const rootDir = path.dirname(path.dirname(path.dirname(fileURLToPath(import.meta.url))));
const target = process.argv[2] ?? "bundler";
const pkgDir = path.join(rootDir, target === "bundler" ? "pkg-bundler" : "pkg-web");
const fixturePath = path.join(rootDir, "example-corpora/en_ulb/43-LUK.usfm");
const ITERATIONS = Number(process.env.ITERATIONS ?? 50);
const WARMUP = 3;

const pkg = await import(pathToFileURL(path.join(pkgDir, "usfm_onion_web.js")).href);
if (target === "web") {
  const wasmBytes = await readFile(path.join(pkgDir, "usfm_onion_web_bg.wasm"));
  await pkg.default({ module_or_path: wasmBytes });
}

const source = await readFile(fixturePath, "utf8");
const sourceBytes = Buffer.byteLength(source, "utf8");

// Pre-parsed inputs for token-in operations (mirroring native:
// parse-once-then-bench-the-op).
const parsed = pkg.parse(source);
const tokens = parsed.tokens();
const editedSource = source + "\\p\n\\v 99 trailing edit\n";
const editedParsed = pkg.parse(editedSource);
const editedTokens = editedParsed.tokens();

function bench(label, fn) {
  for (let i = 0; i < WARMUP; i++) fn();
  const samples = [];
  for (let i = 0; i < ITERATIONS; i++) {
    const start = performance.now();
    fn();
    samples.push(performance.now() - start);
  }
  samples.sort((a, b) => a - b);
  const median = samples[Math.floor(samples.length / 2)];
  const min = samples[0];
  const throughput = sourceBytes / 1024 / 1024 / (median / 1000); // MiB/s
  return { label, medianMs: median, minMs: min, throughputMiBs: throughput };
}

// `pkg.parse(source)` only stashes the source string — the real parse
// happens lazily on each ParsedUsfm method call. So `parse/string` here
// measures parse+tokens-marshal (the smallest unit of actual work that
// crosses the FFI boundary). Source-in operations all include a re-parse
// on every call; that cost is real for JS consumers, even though it
// exaggerates the native-vs-wasm ratio. See `ParsedUsfm` notes in
// docs/plan-wasm-bindings.md for the caching follow-up.

const ops = [
  ["parse/string", () => pkg.parse(source).tokens()],
  ["cst/string", () => pkg.parse(source).cst()],
  ["usj/string", () => pkg.parse(source).toUsj()],
  ["usx/string", () => pkg.parse(source).toUsx()],
  ["html/string", () => pkg.parse(source).toHtml()],
  ["html/tokens", () => pkg.tokensToHtml(tokens)],
  ["lint/string", () => pkg.lintUsfm(source)],
  ["lint/tokens", () => pkg.lintTokens(tokens)],
  ["format/string", () => pkg.formatUsfm(source)],
  ["format/tokens", () => pkg.formatTokens(tokens)],
  ["diff/string", () => pkg.diffUsfm(source, editedSource)],
  ["diff/tokens", () => pkg.diffTokens(tokens, editedTokens)],
  ["vref/string", () => pkg.parse(source).toVref()],
  // Editor's parsedToProjectedDocument pattern: one ParsedUsfm, lint then
  // tokens. Before the cache this paid two parses per call; after, one.
  ["editor/lint+tokens", () => {
    const p = pkg.parse(source);
    p.lint();
    p.tokens();
  }],
  // Workspace-open pattern: same parsed, multiple downstream views.
  ["editor/full-open", () => {
    const p = pkg.parse(source);
    p.tokens();
    p.lint();
    p.cst();
    p.toHtml();
    p.toVref();
  }],
  // Marshalling-only micro-benches: isolate FFI hop cost.
  ["tokens/marshal-out", () => pkg.parse(source).tokens()],
  ["tokens/marshal-in", () => pkg.tokensToUsfm(tokens)],
];

const results = [];
for (const [label, fn] of ops) {
  process.stderr.write(`  ${label} ... `);
  const r = bench(label, fn);
  results.push(r);
  process.stderr.write(`${r.medianMs.toFixed(2)}ms (${r.throughputMiBs.toFixed(1)} MiB/s)\n`);
}

function fmtTime(ms) {
  if (ms >= 1) return `${ms.toFixed(2)} ms`;
  return `${(ms * 1000).toFixed(2)} µs`;
}

const lines = [
  `# WASM bench results`,
  ``,
  `Generated by \`benches/wasm/run.mjs\`. Compare with \`BENCH_RESULTS.md\``,
  `for the native side; same fixture (en_ulb/43-LUK.usfm), same per-op shape.`,
  ``,
  `- Target: ${target}`,
  `- Fixture: 43-LUK.usfm (${(sourceBytes / 1024).toFixed(1)} KiB)`,
  `- Iterations: ${ITERATIONS} (after ${WARMUP} warmup runs); median reported`,
  `- Node: ${process.version}`,
  ``,
  `## operations — String vs. Tokens (per op, on Luke)`,
  ``,
  `| Operation              |    Median |  Throughput |`,
  `| ---------------------- | --------: | ----------: |`,
];
for (const r of results) {
  lines.push(
    `| \`${r.label.padEnd(20)}\` | ${fmtTime(r.medianMs).padStart(9)} | ${r.throughputMiBs.toFixed(1).padStart(6)} MiB/s |`,
  );
}
const report = lines.join("\n") + "\n";

if (process.env.BENCH_OUT) {
  await writeFile(path.join(rootDir, process.env.BENCH_OUT), report);
  process.stderr.write(`wrote ${process.env.BENCH_OUT}\n`);
} else {
  process.stdout.write(report);
}
